### ISSUE TITLE
Update to 4.8.7

### ISSUE THREAD

**Issue by Sereni** [Sereni/Simply-Love-SM5-Vertical#24]

**Comment by Roujo** [comment]
There are so many merge conflicts, it's crazy. 🤣

I'm giving this a shot, but I'll have to test it a bunch to make sure I haven't broken anything. I'll keep you posted.

**Comment by Sereni** [comment]
yeah this one's a unit. thanks! any questions, message me :)

**Comment by Roujo** [comment]
I'm currently doing the update using two strategies at the same time:
- A rebase of your work on top of 4.8.7, which allows me to deal with smaller chunks of code, mostly related to a single feature at a time, but that doesn't really show the overall big picture, and;
- A merge of 4.8.7 to this repo's `master`, which means all changes need to be handled at the same time but then I can see overarching patterns and refactors more easily.

At the moment, both are useful as they contribute to my overall understanding of the codebase - it's my first time delving into a SM theme like this, so that's fun. I haven't contributed to a public codebase like this before, though, so I don't really know which one is the best for a contribution like this.

- The rebase is probably cleaner and less error-prone, since it applies all of the work on top of quietly-turning's work and so makes errors easier to catch as they happen. However, it rewrites a bunch of history, which can be a bit of a pain in a shared, loosely coordinated codebase like this one - it'd work well if everyone rebased their changes against `master` in the course of the work they do, but that's not necessarily intuitive nor user-friendly. 😅 
- The merge solves the latter problem, but is a lot less readable since it's one huge commit that has to be done and reviewed as a single block. It fits into any existing workflow very well, though, since people just have to take in the changes once they're done an everyone can be kept in sync pretty well.

So yeah, I'm not sure which approach is the best here since pretty much all of my development work was either done solo or as part of my employment in a closely coordinated team. I'm currently leaning towards doing the rebase on my end to learn about the code, and then applying that knowledge by doing it again as a merge so that other people's work isn't impacted. How does this sound to you? =)

**Comment by Sereni** [comment]
I don't have a good answer for this — I think your approach of learning via rebase, and then doing a merge in the end is the best we can do. Do ping me on Discord with any questions as you're figuring it out! In the end, I'll set aside a good chunk of time to carefully review and test the mega-commit.

**Comment by Sereni** [comment]
As promised, a couple broken things found today — except for pixels sticking out :)

[ ] In System options, the help text on the bottom is missing a background quad — it's barely visible on either color or rainbow modes. Should be a default grey in color mode, and the same but 70-80% opacity in rainbow
[ ] Player options got mixed up somewhere, at least the bois are missing — need to check row definitions in Metrics.ini and use our pre-merge ones as the source of truth

**Comment by Roujo** [comment]
Nice finds! In order:
- I'm not sure how to add that quad - I'm looking around in `ScreenOptionsService overlay` but there doesn't seem to be any drawing of anything going on there. I guess it's done in the _fallback theme, but I'm not sure where. Do you have any pointers? ^^
- Player options are back, they should match what was present pre-merge. I'll open a PR. =)
- Looks okay to me. Do you have a screenshot? Mine looks like this:
![image](https://user-images.githubusercontent.com/706916/86853718-0f69d980-c085-11ea-96eb-835ca5d30848.png)

The cursors on the options are still misaligned, I haven't found how to fix them yet. Maybe I'll find it eventually! 😅

**Comment by Sereni** [comment]
When logged in as P2 :)

![Screen Shot 2020-07-08 at 11 36 13 AM](https://user-images.githubusercontent.com/4284741/86908988-56041600-c10f-11ea-83c7-6852dcd2597d.png)

**Comment by Sereni** [comment]
Tis done!
