### ISSUE TITLE
Update to 4.9

### ISSUE THREAD

**Issue by Sereni** [Sereni/Simply-Love-SM5-Vertical#56]
[Release notes](https://github.com/quietly-turning/Simply-Love-SM5/releases/tag/4.9)
[Commit history](https://github.com/quietly-turning/Simply-Love-SM5/compare/4.8.7...4.9)

Port relevant features (in order of priority):
- [ ] Measure counter lookahead
- [ ] Color changes
- [ ] Stage count in course mode
- [ ] Profile avatars
- [ ] Italian language support
- [ ] Selectable hold judgments (maybe, if we have space in the options menu)
- [ ] Column spacing in pump
- [ ] Random Background behavior 

Apply fixes (in no particular order):
- [ ] Update Spanish translation
- [ ] Default Fail Setting bug
- [ ] QR code generator to work with ssc files

Review commit history and port other things that look relevant, noting them below.
Currently at commit: [c845ac3](https://github.com/quietly-turning/Simply-Love-SM5/commit/c845ac366ff60c3ba976f238cfd913b4a4d258df)
Things ported:

**Comment by Roujo** [comment]
So I went and merged 4.9 directly instead of cherry-picking, it went a lot better than 4.8.7 did so I suggest we use that instead of cherry-picking features. I think it'll help us in the long run if we keep merging, since we won't have to delve in the commit history to see what's worth bringing over. =)
